### ISSUE TITLE
IEX

### ISSUE THREAD

**Issue by TheMac2017** [qalydon/iex-localc#1]
Cant get it installed in windows.

![2018-04-01 17_31_21-sure dividends ods - libreoffice calc](https://user-images.githubusercontent.com/29148224/38177685-25344cd0-35d3-11e8-829e-c17762d769cf.jpg)

**Comment by dhocker** [comment]
Required directory C:\Users\Me\AppData\libreoffice\iex was not automatically created. Fixed in 0.0.43-alpha release.

**Comment by TheMac2017** [comment]
That fixed it...thanks.
